language: go
sudo: false

notifications:
  slack:
    rooms:
      secure: "L21izvG9BvI3dRVlxachMKKfXwEDDAKMl+lZ7uo3jsTsBf+0nfGgX3f0FTebbTOraPWXQ6U77p2/2WsAokebZOmRTEEF/WPkZ+3I25f0HANCKvI/Ow0KJ3fyDSar46jYCavvxeJtEeYWdaLLGIwmV5v5NxhlIqIybKYdFl86iRS7J4Puw805QamugKH1ardvf4xRLQ8qS/EoD5M9Rm2Q6XkMsrkaS3fIraExmBLUq9ulVzqXyO6berc25aMCfAhk46fgnVHykF9jShAPXqISSFYronztEsvAqnpqcFz0byY6q3w+RtAlA3xVJfGeE3mFrG+OQP4LQ79YFIOdZ8x/cQ1ijBmgnznClb82ji2yg/iDgE/xDDLb29ZUI6eieS0yzZUXFk2jBLIoynaallhQmPjGDYx8FlaK1OEHXjUD2C4uy0rcfb9W4CnF++S4EkYbsBfURYcVH72N2chirg96e20Ejmo9naEI4IXY4x7BGsbjPZ2geVkoEioZR0/CIWK40TBt78+Pp/MUyDO7a2/ek3Y33Pj4T4YCcnanWYZiZvy7WTJpL1pbQYvqZCqhnqbFEtd2IgEmBILKZQheA4FxkIWUschOKKwj49qfR3zpQPoFEi+CJyneyGvmhfNYzhttg/JdlIZiISI9k+LPDF+UIHHByuVdW4uKGT6GgVXBIAA="
    on_success: always
    on_failure: always
    template:
      - "%{repository_slug} %{message} %{duration}"
      - "%{author} : (<%{compare_url}|%{commit}>) %{commit_message}"
      - "Build Details: %{build_url}"

before_script:
  - go get -u github.com/blendlabs/go-assert

script: 
  - go test
